# Generated by Django 3.1.3 on 2022-10-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20221018_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='year_founded',
            field=models.PositiveIntegerField(default=2022),
        ),
    ]
